name=ESP_MOVIE
version=1.0.0
author=ShunTomino
maintainer=ShunTomino
sentence=Movie player library for ESP32/ESP32-S3
paragraph=Movie(MotionJPG/MP3) player library for ESP32/ESP32-S3
category = Display
url=https://github.com/ShunTomino/ESP_MOVIE.git
architectures = esp32
precompiled=true
dot_a_linkage=true